### PR TITLE
Create _index.md

### PR DESCRIPTION
**Pull request by souzatharsis**

### CODE REVIEW

**Comment by verri** [comment]
@souzatharsis , do you want to include a `avatar.jpg` too?

**Comment by souzatharsis** [comment]
avatar

**Comment by souzatharsis** [comment]
github did not allow me to upload the file. there you go.

**Review by verri — APPROVED** [review]

**Comment by verri** [comment]
There you go: https://drone-comp.ita.br/author/tharsis-t.-p.-souza/

**Comment by souzatharsis** [comment]
Thanks!

**Pull request merged**
